#!/usr/bin/env bash
#
# OpenObserve upstream sync.
#
# Rebuilds the OpenObserve browser SDK from a pristine upstream (DataDog/browser-sdk)
# release tag:
#
#   1. checks out the upstream tag on a new sync branch
#   2. restores fork-owned files from the openobserve branch (keep-ours.txt)
#   3. runs the rebrand codemod (rename-map.json)
#   4. regenerates the yarn lockfile
#   5. applies the functional patch series (openobserve-patches/*.patch) with 3-way merge
#   6. records the new upstream base
#
# Usage:
#   scripts/openobserve/sync-upstream.sh [<tag>]
#
#   <tag>        Upstream release tag to sync to (e.g. v7.5.0). When omitted, the latest
#                stable tag with the SAME MAJOR as the recorded base is used.
#   ALLOW_MAJOR=1  Allow the automatic tag selection to cross a major version boundary.
#   UPSTREAM_REMOTE (default: upstream), BASE_BRANCH (default: openobserve)
#
# Exit codes: 0 success (or already up to date), 2 patch application failed (manual
# port needed), 3 blocked on a new major (re-run with an explicit tag or ALLOW_MAJOR=1).
set -euo pipefail

UPSTREAM_REMOTE=${UPSTREAM_REMOTE:-upstream}
BASE_BRANCH=${BASE_BRANCH:-openobserve}
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

if [ -n "$(git status --porcelain -uno)" ]; then
  echo "error: working tree has uncommitted changes to tracked files" >&2
  exit 1
fi

# --force: upstream tags are authoritative (upstream occasionally re-points tags)
git fetch "$UPSTREAM_REMOTE" --tags --prune --force --quiet
git fetch origin "$BASE_BRANCH" --quiet 2>/dev/null || true

# The tooling lives on the openobserve branch, but the working tree is about to become the
# upstream tag. Work from a temp copy so the script and its data files survive the checkout.
TOOLING=$(mktemp -d)
trap 'rm -rf "$TOOLING"' EXIT
git show "$BASE_BRANCH:scripts/openobserve/rebrand.mjs" > "$TOOLING/rebrand.mjs"
git show "$BASE_BRANCH:scripts/openobserve/rename-map.json" > "$TOOLING/rename-map.json"
git show "$BASE_BRANCH:scripts/openobserve/keep-ours.txt" > "$TOOLING/keep-ours.txt"
CURRENT_BASE=$(git show "$BASE_BRANCH:scripts/openobserve/UPSTREAM_BASE" 2>/dev/null || echo 'none')

# ---- Pick the target tag ----------------------------------------------------
TARGET=${1:-}
stable_tags() { git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V; }
if [ -z "$TARGET" ]; then
  if [ "${ALLOW_MAJOR:-0}" = "1" ] || [ "$CURRENT_BASE" = "none" ]; then
    TARGET=$(stable_tags | tail -1)
  else
    MAJOR=${CURRENT_BASE#v}; MAJOR=${MAJOR%%.*}
    TARGET=$(stable_tags | grep "^v$MAJOR\." | tail -1 || true)
    LATEST=$(stable_tags | tail -1)
    if [ -z "$TARGET" ]; then
      echo "error: no stable tag found for major v$MAJOR" >&2
      exit 1
    fi
    if [ "${LATEST%%.*}" != "v$MAJOR" ]; then
      echo "notice: a newer upstream major is available ($LATEST, current base $CURRENT_BASE)."
      echo "notice: majors are not synced automatically; re-run with ALLOW_MAJOR=1 or an explicit tag."
      if [ "$TARGET" = "$CURRENT_BASE" ]; then
        exit 3
      fi
    fi
  fi
fi

if [ "$TARGET" = "$CURRENT_BASE" ]; then
  echo "Already up to date with upstream $TARGET."
  exit 0
fi

echo "Syncing upstream $CURRENT_BASE -> $TARGET"
# The sync branch descends from the openobserve branch (so the PR merges cleanly and its
# diff shows exactly what changes), but its tree is replaced with the upstream tag content.
SYNC_BRANCH="sync/upstream-$TARGET"
git checkout -B "$SYNC_BRANCH" "$BASE_BRANCH"
git rm -rfq . >/dev/null
git checkout "refs/tags/$TARGET^{commit}" -- .
git clean -fd --quiet

# ---- Keep-ours overlay -------------------------------------------------------
# Fork-owned paths are taken from the openobserve branch. Directories are replaced
# wholesale so files deleted on the openobserve branch do not resurrect.
grep -vE '^\s*(#|$)' "$TOOLING/keep-ours.txt" | while read -r path; do
  if git cat-file -e "$BASE_BRANCH:$path" 2>/dev/null; then
    rm -rf "$path"
    git checkout "$BASE_BRANCH" -- "$path"
  else
    echo "keep-ours: '$path' not found on $BASE_BRANCH, skipping"
  fi
done

# ---- Rebrand codemod ----------------------------------------------------------
node "$TOOLING/rebrand.mjs"

# ---- Lockfile ------------------------------------------------------------------
if [ "${SKIP_INSTALL:-0}" != "1" ]; then
  yarn install --no-immutable
fi

# Apache-2.0 §4 attribution gate: fail the sync if Datadog attribution was erased.
node scripts/openobserve/check-attribution.mjs

git add -A
git commit --quiet -m "chore(sync): rebrand upstream $TARGET as OpenObserve browser SDK

Generated by scripts/openobserve/sync-upstream.sh:
- upstream tag: $TARGET
- keep-ours overlay from $BASE_BRANCH
- rebrand codemod (scripts/openobserve/rename-map.json)
- lockfile regenerated"

# ---- Functional patch series ---------------------------------------------------
if ! git am -3 openobserve-patches/*.patch; then
  echo "error: patch application failed. Resolve in the git-am session, then:" >&2
  echo "  git am --continue   # after fixing conflicts" >&2
  echo "  git format-patch --zero-commit -o openobserve-patches <base>..HEAD  # refresh series" >&2
  exit 2
fi

# ---- Record the new base --------------------------------------------------------
echo "$TARGET" > scripts/openobserve/UPSTREAM_BASE
git add scripts/openobserve/UPSTREAM_BASE
git commit --quiet -m "chore(sync): record upstream base $TARGET"

echo
echo "Sync branch $SYNC_BRANCH is ready."
echo "Review, run CI, and open a PR against $BASE_BRANCH."
